### ISSUE TITLE
Debuffed Consumable cards crash game during scoring

### ISSUE THREAD

**Issue by jumbocarrot0** [Steamodded/smods#384]
The cause seems to be a BetterCalc patch for `eval_card` that returns a single table for non-joker debuffed cards (rather than returning two for any post triggers).

```toml
## eval_card()
# handle debuffed playing cards
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
function eval_card(card, context)
    context = context or {}
    local ret = {}
'''
position = 'at'
match_indent = true
payload = '''
function eval_card(card, context)
    if card.ability.set ~= 'Joker' and card.debuff then return {} end
    context = context or {}
    local ret = {}
'''
```

[Download for the crash log in the video](https://github.com/user-attachments/files/18370254/Crash.Log.txt)

https://github.com/user-attachments/assets/e34566e6-be06-4b4e-8743-8f0eee6e4648
